[package]
name = "josette"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
byteorder = "1.4.3"
hexyl = "0.10.0"
nom = "7.1.1"
tribool = "0.3.0"
